/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-116122-gd241edc2b4-20240703"
#endif /* AVUTIL_FFVERSION_H */
